### ISSUE TITLE
Create a getgrav cms plugin to list the contributors of all tedxamsterdam projects ranked on activity [php]

### ISSUE THREAD

**Issue by dligthart** [TEDxAmsterdam/Community-Portal#1]
To give thanks to all the contributors we would like to list everyone on http://dev.tedx.amsterdam/contributors. This is a small project to create a plugin based on the github api statistics : 

https://developer.github.com/v3/repos/statistics/

Acceptance criteria:
1. List all contributors (no pagination) from different open source projects (front-end, back-end and community portal) in one big list.
2. Rank contributors on activity (sorted most activity to least activity)
3. Per retrieved item; get avatar and username and link to github profile 
4. Stylesheets should be defined in the theme; the plugin can't enforce the styling
5. Provide instructions how to configure and install the plugin and how to add custom styling
6. (1) Provide a plugin configuration page in admin to set the github credentials and (2) to specify the github repositories to aggregate users from.
7. This is a plugin for the https://getgrav.org/ (only the user files of the current installation are provided in this repository ; you need to make a local installation of the getgrav cms)

Mockup:

![contributors-community-portal-page2](https://cloud.githubusercontent.com/assets/25735/14106132/9bd05250-f5af-11e5-82ed-f90e5f27e06d.png)

**Comment by Randynamic** [comment]
I know the FE guys always take all the credit :laughing:. But IMHO it would be nice to have an overal contributors view which you can filter. So everyone is listed in the primary view #teamEffort. 
@dligthart what do you  think about that?

**Comment by dligthart** [comment]
Yes I agree, so no tabs but a nice list view.

**Comment by dligthart** [comment]
I have updated the mockup.

**Comment by dligthart** [comment]
Live: http://dev.tedx.amsterdam/contributors
